root: true
env:
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
rules:
  "@typescript-eslint/quotes":
    - error
    - double
    - avoidEscape: true
      allowTemplateLiterals: false
  "@typescript-eslint/semi":
    - error
    - never