stages:
- linting
- building

lint:
  stage: linting
  image: node:14-alpine
  before_script:
    - npm ci
  script:
    - npm run lint

build:
  stage: building
  image: node:14-alpine
  before_script:
    - npm ci
  script:
    - npm run build
