stages:
  - validating
  - deploying

validate:
  stage: validating
  image: registry.gitlab.com/yellowgarbagegroup/docker-images/node-with-pnpm:14-alpine
  script:
    - echo DATABASE_URL=file:./dev.db > .env
    - pnpm i
    - ./node_modules/.bin/prisma generate
    - pnpm run lint
    - pnpm run build

dockerize:
  stage: deploying
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest
