stages:
  - validating
  - dockerize


validate:
  stage: validating
  image: node:14-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov

docker:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
#  only:
#    - tags
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
