stages:
  - building
  - deploying

lbt:
  stage: building
  image: node:14-alpine
  tags:
    - Yellow
  script:
    - npm i pnpm -g
    - pnpm i -r

    - cd sw-shared
    #- pnpm run lint
    - pnpm run build
    #- pnpm run test
    - cd ..

    - cd sw-api
    #- pnpm run lint
    - echo DATABASE_URL=file:./dev.db > .env
    - ./node_modules/.bin/prisma generate
    - pnpm run build
    #- pnpm run test
    - cd ..

    #- cd sw-ui
    #- pnpm run lint
    #- pnpm run build
    #- pnpm run test
    #- cd ..

dockerize:
  stage: deploying
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - Yellow
  only:
    - main
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
