# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- validate
- deploy
- test
workflow:
  rules:
  - if: "$CI_MERGE_REQUEST_ID"
    when: never
  - when: always
validate-job:
  stage: validate
  image: registry.gitlab.com/4s1/docker/node:14-alpine-dev
  rules:
  - if: "$CI_COMMIT_TAG == null"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - ".pnpm-store"
  before_script:
  - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
  - pnpm i
  - pnpm run lint
  - pnpm run build
deploy-job:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ''
  rules:
  - if: "$CI_COMMIT_TAG != null"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - ".pnpm-store"
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}
    | base64)\"}}}" > /kaniko/.docker/config.json
  - "/kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
    --destination $CI_REGISTRY_IMAGE:latest"
sast:
  variables:
    SEARCH_MAX_DEPTH: '2'
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
