stages:
  - building
  - testing

build:
  stage: building
  image: node:12-alpine
  before_script:
    - npm ci
  script:
    - npm run build

test:
  stage: testing
  image: node:12-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  before_script:
    - npm ci
  script:
    - npm run test:cov
