stages:
  - validation

validate-all:
  stage: validation
  image: node:14-alpine
  tags:
    - Yellow
  script:
    - npm i pnpm -g
    - pnpm i

    - cd sw-shared
    #- pnpm run lint
    - pnpm run build
    #- pnpm run test
    - cd ..

    - cd sw-api
    #- pnpm run lint
    - ./node_modules/.bin/prisma generate
    - pnpm run build
    #- pnpm run test
    - cd ..

    #- cd sw-ui
    #- pnpm run lint
    #- pnpm run build
    #- pnpm run test
    #- cd ..
